package com.closedcircuit.closedcircuitapplication.common.presentation.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF376A20)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFB7F397)
internal val md_theme_light_onPrimaryContainer = Color(0xFF072100)
internal val md_theme_light_secondary = Color(0xFF55624C)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFD8E7CB)
internal val md_theme_light_onSecondaryContainer = Color(0xFF131F0D)
internal val md_theme_light_tertiary = Color(0xFF386667)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFBBEBEC)
internal val md_theme_light_onTertiaryContainer = Color(0xFF002020)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFDFDF6)
internal val md_theme_light_onBackground = Color(0xFF1A1C18)
internal val md_theme_light_surface = Color(0xFFFDFDF6)
internal val md_theme_light_onSurface = Color(0xFF1A1C18)
internal val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
internal val md_theme_light_onSurfaceVariant = Color(0xFF43483E)
internal val md_theme_light_outline = Color(0xFF74796D)
internal val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
internal val md_theme_light_inverseSurface = Color(0xFF2F312D)
internal val md_theme_light_inversePrimary = Color(0xFF9CD67E)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF376A20)
internal val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF9CD67E)
internal val md_theme_dark_onPrimary = Color(0xFF103800)
internal val md_theme_dark_primaryContainer = Color(0xFF205107)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFB7F397)
internal val md_theme_dark_secondary = Color(0xFFBDCBB0)
internal val md_theme_dark_onSecondary = Color(0xFF283420)
internal val md_theme_dark_secondaryContainer = Color(0xFF3E4A36)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFD8E7CB)
internal val md_theme_dark_tertiary = Color(0xFFA0CFD0)
internal val md_theme_dark_onTertiary = Color(0xFF003738)
internal val md_theme_dark_tertiaryContainer = Color(0xFF1E4E4F)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFBBEBEC)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1A1C18)
internal val md_theme_dark_onBackground = Color(0xFFE3E3DC)
internal val md_theme_dark_surface = Color(0xFF1A1C18)
internal val md_theme_dark_onSurface = Color(0xFFE3E3DC)
internal val md_theme_dark_surfaceVariant = Color(0xFF43483E)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
internal val md_theme_dark_outline = Color(0xFF8D9286)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
internal val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
internal val md_theme_dark_inversePrimary = Color(0xFF376A20)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF9CD67E)
internal val md_theme_dark_outlineVariant = Color(0xFF43483E)
internal val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF24500F)

val primary1 = Color(0xFF376A20)
val primary2 = Color(0xFF76961F)
val primary3 = Color(0xFFBFEEFBCD)
val primary4 = Color(0xFF2E7C36)
val primary5 = Color(0xFFB7E143)

val secondary1 = Color(0xFFD91D1D)
val secondary2 = Color(0xFFFF9234)
val secondary3 = Color(0xFFFEF6E9)
val secondary4 = Color(0xFFBFFCF3E8)
val secondary5 = Color(0xFFD7A949)

val accent1 = Color(0xFF5153F1)
val accent2 = Color(0xFFBFD1F7FF)
val accent3 = Color(0xFFBFEAEEFE)
val accent4 = Color(0xFF060A62)
